# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [4]:
import sys

import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
print(np.__version__)

1.23.5


#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
zero_vect = np.zeros(10, dtype=np.int64)
zero_vect

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

#### 4. How to find the memory size of any array (★☆☆)

In [7]:
zero_vect.nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [8]:
np.add.__doc__
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
vect_fifth_1 = np.zeros(10, dtype=np.int64)
vect_fifth_1[4]=1
vect_fifth_1

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64)

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
arr_10_to_49 = np.arange(10,50)
arr_10_to_49

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [11]:
reversed_arr = np.flip(arr_10_to_49)
reversed_arr

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
A = np.arange(9).reshape((3,3))
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [13]:
arr = [1,2,0,0,4,0]
(np.nonzero(arr))

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [14]:
np.identity(3,dtype=np.int64)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int64)

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [15]:
np.random.rand(3,3,3)
# np.random.randint(3000, size=(3,3,3))

array([[[0.4304544 , 0.35241015, 0.09047922],
        [0.42818335, 0.39174487, 0.14037846],
        [0.06619232, 0.87139407, 0.96400313]],

       [[0.361606  , 0.31045857, 0.49388078],
        [0.90722473, 0.63015443, 0.65929846],
        [0.07946491, 0.93073435, 0.90506708]],

       [[0.07877054, 0.73751888, 0.71201811],
        [0.73577617, 0.73094148, 0.24020542],
        [0.62144218, 0.66748406, 0.34567981]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [16]:
rng = np.random.default_rng()
arr1 = rng.integers(100,size=(10,10))
print(arr1)
print(np.amax(arr1), np.amin(arr1))


[[43  2 69 78 52 41 85  3 70 15]
 [80 52 45 16 49 95 88 55 38 13]
 [54 74 36 45 38 86 26 33 26 43]
 [71 53 85 96 35 89 52 99 85 35]
 [35 64 59 79 82 13 42 92 61 28]
 [47 90 60 65 87 57 32 60 71 53]
 [90 41 35 23 87 98 16 92  0 48]
 [58 15 40 60 22 33  6  1  8 23]
 [82 24 17 84 34 46  5 44  6 84]
 [44 39 16  2 84 23  8 42 68 25]]
99 0


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [17]:
vect_30  = rng.integers(15, size=30)
print(vect_30)
print(np.mean(vect_30))

[ 1  2  2 14 11  4 12  5 11  5 14 12 11  7 10  8 10  4  1  5 14 14  6 12
  0  5  5  7  6 11]
7.633333333333334


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [18]:
arr_border_1 = np.ones((10,10), dtype=np.int64)
arr_border_1[1:-1,1:-1] = 0
arr_border_1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int64)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [19]:
arr_border_1 = np.ones((10,10), dtype=np.int64)
np.pad(arr_border_1,1)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [20]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [21]:
matrix_below_diag = np.diag(np.arange(1,5),k=-1)
matrix_below_diag

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [22]:
np.indices((8,8)).sum(axis=0) % 2

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int32)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [23]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [24]:
np.tile( np.array([[0,1],[1,0]]), (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [25]:
rand_matrix = rng.random(size=(5,5))
row_sums = rand_matrix.sum(axis=1)
normed_matrix = rand_matrix / row_sums[:, np.newaxis]
normed_matrix

array([[0.31100292, 0.3461391 , 0.17751023, 0.13267815, 0.03266959],
       [0.23654389, 0.25339089, 0.05548669, 0.18343978, 0.27113874],
       [0.18978785, 0.088651  , 0.03652182, 0.44210614, 0.2429332 ],
       [0.12163531, 0.27339525, 0.21024776, 0.39297247, 0.0017492 ],
       [0.27244723, 0.41220525, 0.19510605, 0.0911126 , 0.02912887]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [26]:
color_t = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
image = np.array([(25, 33, 33, 255), (53, 66, 167, 255), (191, 11, 10, 60)], dtype = color_t)
image

array([( 25, 33,  33, 255), ( 53, 66, 167, 255), (191, 11,  10,  60)],
      dtype=[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [27]:
matrix1= rng.integers(10,size=(5,3))
matrix2= rng.integers(10,size=(3,2))
res = np.matmul(matrix1,matrix2)
print(matrix1)
print(matrix2)
print(res)


[[9 7 8]
 [9 6 1]
 [8 7 3]
 [2 2 2]
 [5 6 5]]
[[3 1]
 [6 1]
 [1 8]]
[[77 80]
 [64 23]
 [69 39]
 [20 20]
 [56 51]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [28]:
arr1d = np.arange(23)
arr1d[(arr1d > 3) & (arr1d < 8)] = -arr1d[(arr1d > 3) & (arr1d < 8)]
arr1d

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [29]:
print(sum(range(5),-1))#9
from numpy import *
print(sum(range(5),-1))#10

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [30]:
Z = rng.integers(10,size=10)

print(Z ** Z)
print(2 << Z >> 2)
print(Z < - Z)
print(1j * Z)
print(Z / 1 / 1)
# print(Z < Z > Z)


[        4     46656    823543 387420489 387420489     46656         1
       256         1      3125]
[  2  32  64 256 256  32   1   8   1  16]
[False False False False False False False False False False]
[0.+2.j 0.+6.j 0.+7.j 0.+9.j 0.+9.j 0.+6.j 0.+1.j 0.+4.j 0.+1.j 0.+5.j]
[2. 6. 7. 9. 9. 6. 1. 4. 1. 5.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [31]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\VIP\AppData\Local\Temp\ipykernel_6896\1422587819.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\VIP\AppData\Local\Temp\ipykernel_6896\1422587819.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [32]:
not_rounded = np.random.uniform(-10, +10, 10)
res = np.copysign(np.ceil(abs(not_rounded)), not_rounded)
print(not_rounded)
print(res)

[-0.0117256   6.9124344   1.48835752  7.59493846 -7.92483401 -9.19429693
 -6.42525127  7.83254745 -6.17602211  7.43905381]
[ -1.   7.   2.   8.  -8. -10.  -7.   8.  -7.   8.]


#### 30. How to find common values between two arrays? (★☆☆)

In [33]:
arr_inter_res = np.intersect1d(['Ivan', 'Kolya', 'Vasya', 'Petya', 'Evkakiy'], ['Borya', 'Stepa', 'Vasya', 'Misha', 'Evkakiy'])
arr_inter_res

array(['Evkakiy', 'Vasya'], dtype='<U7')

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [34]:
np.seterr(all="ignore")
arr_1 = np.array([1])
arr_0 = np.array([0])
Output = arr_1 / arr_0
print(Output)

[inf]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [35]:
np.sqrt(-1) == np.emath.sqrt(-1)#Перша повертає нан друга комплексне число

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [36]:
today = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

2022-11-30 2022-12-01 2022-12-02


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [37]:
print(np.arange('2016-07', '2016-08',
                dtype='datetime64[D]'))


['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [38]:
A = np.ones(5)
B = np.ones(5) * 2
np.add(A, B, out=B)
np.negative(A, out=A)
np.divide(A, 2, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [39]:
arr_extr = np.random.uniform(0, +10, 10)
print(arr_extr)
print(np.ceil(arr_extr))
print(arr_extr.astype(np.int32))
print(np.rint(arr_extr))#nearest
print(np.trunc(arr_extr))

[5.62208421 7.92433399 8.01216832 7.63789706 8.87742538 5.49906089
 2.58034755 3.59602196 2.56505689 4.61809182]
[6. 8. 9. 8. 9. 6. 3. 4. 3. 5.]
[5 7 8 7 8 5 2 3 2 4]
[6. 8. 8. 8. 9. 5. 3. 4. 3. 5.]
[5. 7. 8. 7. 8. 5. 2. 3. 2. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [40]:
np.indices((5,5))[1]

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [41]:
def generator_func():
   for x in range(10):
       yield x
np.fromiter(generator_func(),dtype=np.int32,count=-1)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [42]:
x = np.linspace(0,1,12)[1:-1]
x

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [43]:
vect_40 = rng.random(10)
print(vect_40)
sorted_40 = np.sort(vect_40)
sorted_40

[0.09247597 0.96985735 0.47623396 0.20158495 0.09779698 0.08036848
 0.35446854 0.1044257  0.65641161 0.97838009]


array([0.08036848, 0.09247597, 0.09779698, 0.1044257 , 0.20158495,
       0.35446854, 0.47623396, 0.65641161, 0.96985735, 0.97838009])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [44]:
arr_41 = np.arange(10000)
np.add.reduce(arr_41)

49995000

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [45]:
A_42 = rng.integers(1,5,size=3)
B_42 = rng.integers(1,5,size=3)
print(A_42, B_42)
print(np.array_equal(A_42,B_42))
print(np.allclose(A_42, B_42, atol=1))


[4 2 1] [4 3 1]
False
True


#### 43. Make an array immutable (read-only) (★★☆)

In [46]:
arr_43  = np.zeros(10)
arr_43.setflags(write=False)
#arr_43[0]=1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [47]:
np.set_printoptions(precision=3)
A_44 = np.random.uniform(low=-10, high=10, size=(10,2))
X_44 = A_44[:, 0]
Y_44 = A_44[:, 1]
print(X_44)
print(Y_44)
R = np.sqrt(X_44**2+Y_44**2)
T = np.arctan2(Y_44,X_44)
print(R)
print(T)




[-0.364 -9.279  4.684  0.48  -7.782 -1.813  9.798  8.993 -5.768 -6.411]
[-1.664 -7.661 -0.389  6.171 -1.101 -2.018  9.806 -8.098  0.028  4.754]
[ 1.703 12.033  4.701  6.19   7.859  2.713 13.862 12.102  5.768  7.981]
[-1.786 -2.451 -0.083  1.493 -3.001 -2.303  0.786 -0.733  3.137  2.504]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [48]:
vect_45 = np.random.uniform(low=-100, high=100, size=10)
print(vect_45)
vect_45[np.argmax(vect_45)] = 0
print(vect_45)


[ 24.956  68.123 -95.346 -11.406 -73.91   30.317  82.706  45.488 -72.153
 -82.886]
[ 24.956  68.123 -95.346 -11.406 -73.91   30.317   0.     45.488 -72.153
 -82.886]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [49]:
arr_46 = np.zeros((5,5), [('x', np.float64),('y', np.float64)])
arr_46['x'], arr_46['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(arr_46)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [50]:
X_47 = np.array([1,2,3,4]) #x
Y_47 = np.array([5,6,7])   #y
X_47 = X_47[:,np.newaxis]
print(X_47)
diff_matrix = X_47-Y_47
print(diff_matrix)
cauchym = 1.0/diff_matrix
print(cauchym)


[[1]
 [2]
 [3]
 [4]]
[[-4 -5 -6]
 [-3 -4 -5]
 [-2 -3 -4]
 [-1 -2 -3]]
[[-0.25  -0.2   -0.167]
 [-0.333 -0.25  -0.2  ]
 [-0.5   -0.333 -0.25 ]
 [-1.    -0.5   -0.333]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [51]:
for itype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(itype).min)
   print(np.iinfo(itype).max)
for ftype in [np.float32, np.float64]:
   print(np.finfo(ftype).min)
   print(np.finfo(ftype).max)
   print(np.finfo(ftype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [52]:
np.set_printoptions(threshold=sys.maxsize)
arr_49 = np.zeros((10,10))
print(arr_49)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [53]:
vect_50 = np.random.uniform(0,15,size=15)
print(vect_50)
rand_scalar_50 = np.random.uniform(0,15)
print(rand_scalar_50)
index = (np.abs(vect_50-rand_scalar_50)).argmin()
print(vect_50[index])

[ 1.577  7.645  9.143  6.871  3.315  0.508 10.082  3.911  8.729 10.629
 14.47   3.47   2.107  1.779 12.083]
11.124316182039353
10.629302679377497


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [54]:
arr_51 = np.zeros(10,       [ ('position', [ ('x', float),
                                             ('y', float)]),
                              ('color', [ ('r', float),
                                          ('g', float),
                                          ('b', float)])])
print(arr_51)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [55]:
vect_52 = np.random.uniform(-10,10,(5,2))
X = np.atleast_2d(vect_52[:,0])
Y = np.atleast_2d( vect_52[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[ 0.     9.063 20.972  3.161  8.862]
 [ 9.063  0.    13.455  8.568  1.462]
 [20.972 13.455  0.    21.597 14.692]
 [ 3.161  8.568 21.597  0.     7.87 ]
 [ 8.862  1.462 14.692  7.87   0.   ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [56]:
arr_53 = np.linspace(0,10, 12, dtype=np.float32).astype(np.int32)
arr_53


array([ 0,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [107]:
from io import StringIO
file_text = StringIO("""1, 2, 3, 4, 5\n
                        6,  ,  , 7, 8\n
                          ,  , 9,10,11\n""")
arr_54 = np.genfromtxt(file_text, delimiter=",", dtype=np.int32, missing_values=' ', filling_values=-1)
print(arr_54)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [58]:
arr_55 = np.arange(9).reshape(3,3)
for index, x in np.ndenumerate(arr_55):
    print(index, x)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [59]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X**2+Y**2)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.368 0.448 0.52  0.574 0.603 0.603 0.574 0.52  0.448 0.368]
 [0.448 0.546 0.633 0.699 0.734 0.734 0.699 0.633 0.546 0.448]
 [0.52  0.633 0.734 0.811 0.852 0.852 0.811 0.734 0.633 0.52 ]
 [0.574 0.699 0.811 0.895 0.94  0.94  0.895 0.811 0.699 0.574]
 [0.603 0.734 0.852 0.94  0.988 0.988 0.94  0.852 0.734 0.603]
 [0.603 0.734 0.852 0.94  0.988 0.988 0.94  0.852 0.734 0.603]
 [0.574 0.699 0.811 0.895 0.94  0.94  0.895 0.811 0.699 0.574]
 [0.52  0.633 0.734 0.811 0.852 0.852 0.811 0.734 0.633 0.52 ]
 [0.448 0.546 0.633 0.699 0.734 0.734 0.699 0.633 0.546 0.448]
 [0.368 0.448 0.52  0.574 0.603 0.603 0.574 0.52  0.448 0.368]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [60]:
n = 5
p = 3
arr_57 = np.zeros((n,n))
np.put(arr_57, np.random.choice(range(n*n), p, replace=False),1)
print(arr_57)

[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [61]:
X = np.random.rand(5, 10)
Y = X - np.mean(X,axis=1, keepdims=True)

print(Y)

[[-0.031  0.311 -0.003 -0.418  0.2   -0.2   -0.299  0.207  0.26  -0.026]
 [-0.128 -0.138  0.285  0.11   0.025 -0.12   0.026 -0.181  0.337 -0.217]
 [-0.216  0.139 -0.322 -0.026  0.454  0.112  0.043  0.257 -0.123 -0.318]
 [-0.143  0.229  0.092 -0.153  0.103  0.187  0.047  0.028 -0.14  -0.251]
 [-0.316 -0.332  0.302  0.462  0.508  0.232 -0.076 -0.408 -0.363 -0.009]]


#### 59. How to sort an array by the nth column? (★★☆)

In [62]:

arr_59 = np.random.randint(0,10,(3,3))

print(arr_59)
print(np.argsort(arr_59[:,1]))
print(arr_59[np.argsort(arr_59[:,1])])

[[8 2 9]
 [2 2 5]
 [1 8 7]]
[0 1 2]
[[8 2 9]
 [2 2 5]
 [1 8 7]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [63]:
arr_60 = rng.integers(0,3,(3,10))
print(arr_60)
print((~arr_60.any(axis=0)).any())

[[0 0 1 1 0 1 2 0 2 2]
 [0 1 2 0 0 2 0 0 1 2]
 [2 0 2 1 2 2 0 1 0 2]]
False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [64]:
arr_61 = np.random.uniform(0,1,10)

print(arr_61)

given_val_61 = 0.5

print(arr_61[np.abs(arr_61 - given_val_61).argmin()])

[0.036 0.216 0.177 0.473 0.839 0.249 0.535 0.084 0.533 0.433]
0.4728680017639111


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [65]:
A_62 = np.arange(3).reshape(3,1)

B_62 = np.arange(3).reshape(1,3)

it = np.nditer([A_62,B_62,None])

for A_62_op,B_62_op,C_62_op in it: C_62_op[...] = A_62_op + B_62_op
print(it.operands)
print(it.operands[2])

(array([[0],
       [1],
       [2]]), array([[0, 1, 2]]), array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]]))
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [66]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

obj_arr_63 = NamedArray(np.arange(10), "range_10")
print (obj_arr_63.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [67]:

vect_64 = np.ones(10)
print(vect_64)
indices_64 = np.random.randint(0,len(vect_64),10)
unique_indices_64 = np.unique(indices_64)
print(indices_64)
print(unique_indices_64)
# vect_64 += np.bincount(indices_64, minlength=len(vect_64))
# print(vect_64)

np.add.at(vect_64, unique_indices_64, 1)
print(vect_64)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[4 0 6 5 3 8 1 7 0 3]
[0 1 3 4 5 6 7 8]
[2. 2. 1. 2. 2. 2. 2. 2. 2. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [68]:
X_65 = [1,2,3,4,5,6]
I_65 = np.array([1,3,9,3,4,1])
F_65 = np.bincount(I_65,X_65)
print(F_65)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [69]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [70]:
A_67 = np.random.randint(0,10,(3,4,3,4))
print(A_67)
sum = A_67.sum(axis=(-2,-1))
print(sum)



[[[[1 5 6 6]
   [0 1 3 3]
   [3 2 4 0]]

  [[7 9 9 0]
   [1 7 7 5]
   [2 3 5 4]]

  [[6 2 9 6]
   [8 4 2 6]
   [7 7 2 8]]

  [[9 8 1 7]
   [7 1 3 1]
   [4 7 5 6]]]


 [[[9 6 9 1]
   [2 3 7 6]
   [0 4 5 0]]

  [[2 1 0 9]
   [4 1 9 1]
   [2 9 4 6]]

  [[9 1 6 2]
   [4 6 5 2]
   [6 1 1 9]]

  [[4 6 9 9]
   [3 8 6 3]
   [6 2 8 8]]]


 [[[5 1 6 0]
   [1 3 5 3]
   [9 4 9 5]]

  [[7 4 8 6]
   [2 3 7 2]
   [7 3 1 5]]

  [[6 9 3 8]
   [1 2 1 3]
   [6 2 1 4]]

  [[8 2 2 6]
   [9 0 2 4]
   [7 4 9 8]]]]
[[34 59 67 59]
 [52 48 52 72]
 [51 55 46 61]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [71]:
D_68 = np.random.uniform(0,1,100)
S_68 = np.random.randint(0,10,100)
D_sums_68 = np.bincount(S_68, weights=D_68)
D_counts_68 = np.bincount(S_68)
D_means_68 = D_sums_68 / D_counts_68
print(D_means_68)

[0.573 0.58  0.444 0.441 0.535 0.481 0.41  0.408 0.43  0.542]


#### 69. How to get the diagonal of a dot product? (★★★)

In [72]:
A_69 = np.random.randint(1,3,(4,4))
B_69 = np.random.randint(1,3,(4,4))
np.dot(A_69, B_69)
np.diag(np.dot(A_69, B_69))

array([12, 10,  7,  9])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [73]:
vect_70 = np.array([1,2,3,4,5])
no_zeros = 3
vect_zeros_70 = np.zeros(len(vect_70) + (len(vect_70)-1)*(no_zeros))
vect_zeros_70[::no_zeros+1] = vect_70
print(vect_zeros_70)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [74]:
arr1_71 = np.ones((5,5,3))
arr2_71 = 2*np.ones((5,5))
print(arr1_71 * arr2_71[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [75]:
arr_72 = np.arange(25).reshape(5,5)
print(arr_72)
arr_72[[0,1]] = arr_72[[1,0]]
print(arr_72)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [76]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 4, 20) ( 4, 61) ( 8, 36) ( 8, 76) (13, 38) (13, 65) (18, 27) (18, 57)
 (20, 61) (27, 57) (28, 42) (28, 79) (34, 43) (34, 80) (36, 76) (38, 65)
 (41, 74) (41, 87) (42, 79) (43, 80) (50, 73) (50, 93) (64, 67) (64, 80)
 (67, 80) (73, 93) (74, 87) (76, 88) (76, 95) (88, 95)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [77]:
C_74 = np.bincount([1,1,2,3,4,4,6])
A_74 = np.repeat(np.arange(len(C_74)), C_74)
print(A_74)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [78]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
arr_75 = np.arange(20)
print(moving_average(arr_75, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [79]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [80]:
arr1_77 = rng.integers(0,2,100)
print (arr1_77)
print(np.logical_not(arr1_77, out=arr1_77))


arr2_77 = np.random.uniform(-1.0,1.0,10)
print (arr2_77)
print(np.negative(arr2_77, out=arr2_77))

[0 1 1 0 0 0 0 1 1 0 1 1 0 0 1 0 0 1 0 0 1 1 1 0 0 1 0 1 0 1 1 0 1 1 0 0 1
 0 1 0 0 0 1 0 1 1 0 0 0 1 0 1 1 1 0 0 0 1 0 0 1 0 1 1 1 1 1 0 0 0 0 1 0 0
 0 1 0 0 1 1 0 0 1 0 1 1 1 1 1 0 0 1 0 1 1 1 0 1 1 0]
[1 0 0 1 1 1 1 0 0 1 0 0 1 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0 1 0 0 1 0 0 1 1 0
 1 0 1 1 1 0 1 0 0 1 1 1 0 1 0 0 0 1 1 1 0 1 1 0 1 0 0 0 0 0 1 1 1 1 0 1 1
 1 0 1 1 0 0 1 1 0 1 0 0 0 0 0 1 1 0 1 0 0 0 1 0 0 1]
[ 0.35   0.901 -0.584  0.305  0.609  0.973  0.721  0.762  0.08   0.216]
[-0.35  -0.901  0.584 -0.305 -0.609 -0.973 -0.721 -0.762 -0.08  -0.216]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [81]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[5.641 4.412 2.52  3.214 3.448 0.167 8.52  0.032 4.657 1.588]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [82]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[14.477  8.889  0.038  8.72   4.84   8.563  4.511 12.368 10.17   4.222]
 [ 3.63  10.428 14.859  6.092 14.348  8.259  5.728  7.305  7.247 12.075]
 [ 1.911  4.007  3.6    6.691  0.458  9.414  9.465  4.168  5.315  5.885]
 [11.895  1.043  6.992  4.263  3.016  1.048  6.914  4.809 10.953  3.17 ]
 [ 9.725  4.799  1.797  3.485  0.862  5.92   2.198  7.622  6.897  1.812]
 [ 2.361  5.19   6.025  9.712  8.839  0.359  3.951  4.084  1.612  3.872]
 [ 4.9    7.189  3.356  0.045  3.446 10.306  4.407  8.597  0.596  6.44 ]
 [12.891  6.211  1.983  6.596  2.183  6.262  4.593  9.622  9.675  1.997]
 [ 2.097  4.129  3.83   6.815  0.587  9.615  9.74   4.231  5.572  6.095]
 [12.536  8.858  1.048  7.052  4.876  9.256  2.498 11.882  8.086  5.011]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [83]:

from numpy.lib import stride_tricks
Z_81 = np.arange(1,15,dtype=np.uint32)
resarr_81 = stride_tricks.as_strided(Z_81,(11,4),(4,4))
print(resarr_81)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [84]:
Z_82 = np.arange(1,15,dtype=int)
Res_arr = stride_tricks.as_strided(Z_82,(11,4),(4,4))
print(R)

[ 1.703 12.033  4.701  6.19   7.859  2.713 13.862 12.102  5.768  7.981]


#### 83. How to find the most frequent value in an array?

In [85]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [86]:
Z = np.random.randint(0,5,(10,10))
print(Z)
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[3 4 1 4 2 2 0 0 2 4]
 [0 0 3 2 0 4 1 0 0 2]
 [2 3 2 1 2 2 0 3 3 0]
 [2 4 4 0 0 0 1 4 2 2]
 [1 1 1 2 4 4 3 0 0 1]
 [0 1 2 4 3 4 2 1 4 2]
 [4 4 0 2 3 1 3 3 2 3]
 [2 1 3 0 2 4 4 3 4 3]
 [3 1 3 0 2 0 4 3 2 0]
 [2 0 1 4 2 4 1 0 1 0]]
[[[[3 4 1]
   [0 0 3]
   [2 3 2]]

  [[4 1 4]
   [0 3 2]
   [3 2 1]]

  [[1 4 2]
   [3 2 0]
   [2 1 2]]

  [[4 2 2]
   [2 0 4]
   [1 2 2]]

  [[2 2 0]
   [0 4 1]
   [2 2 0]]

  [[2 0 0]
   [4 1 0]
   [2 0 3]]

  [[0 0 2]
   [1 0 0]
   [0 3 3]]

  [[0 2 4]
   [0 0 2]
   [3 3 0]]]


 [[[0 0 3]
   [2 3 2]
   [2 4 4]]

  [[0 3 2]
   [3 2 1]
   [4 4 0]]

  [[3 2 0]
   [2 1 2]
   [4 0 0]]

  [[2 0 4]
   [1 2 2]
   [0 0 0]]

  [[0 4 1]
   [2 2 0]
   [0 0 1]]

  [[4 1 0]
   [2 0 3]
   [0 1 4]]

  [[1 0 0]
   [0 3 3]
   [1 4 2]]

  [[0 0 2]
   [3 3 0]
   [4 2 2]]]


 [[[2 3 2]
   [2 4 4]
   [1 1 1]]

  [[3 2 1]
   [4 4 0]
   [1 1 2]]

  [[2 1 2]
   [4 0 0]
   [1 2 4]]

  [[1 2 2]
   [0 0 0]
   [2 4 4]]

  [[2 2 0]
   [0 0 1]
   [4 4 3]]

  [[2 0 3]
   [0 1 4]
   [4 3 

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [87]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 4  6 17 15  8]
 [ 6  2  8  9  9]
 [17  8  8 42  5]
 [15  9 42  9  7]
 [ 8  9  5  7  1]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [88]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [89]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [90]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★)

In [91]:
arr_89 = np.random.randint(1,20,10)
print(arr_89)
n = 3
print (arr_89[np.argsort(arr_89)[-n:]])

[17 17 10  1 14  4  6  5 15 15]
[15 17 17]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [92]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [93]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [103]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

6.2 s ± 1.75 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
551 ms ± 29.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
354 ms ± 41.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
4.03 s ± 176 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
798 ms ± 226 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
392 ms ± 48.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [95]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
print("A: \n", A)
print("B: \n", B)
C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print("Rows: \n", rows)

A: 
 [[2 3 3]
 [3 4 3]
 [4 1 1]
 [1 4 1]
 [1 4 3]
 [2 2 2]
 [1 3 3]
 [0 1 3]]
B: 
 [[1 1]
 [0 1]]
Rows: 
 [2 3 4 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [96]:
Z = np.random.randint(0,2,(10,3))
print(Z)
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print("Rows with unequal values: \n", U)

[[1 0 1]
 [0 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 1]
 [0 0 1]
 [0 1 1]
 [0 1 0]
 [1 1 0]
 [1 1 1]]
Rows with unequal values: 
 [[1 0 1]
 [0 1 0]
 [0 0 1]
 [1 0 1]
 [0 0 1]
 [0 1 1]
 [0 1 0]
 [1 1 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [104]:
intvect_95 = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(intvect_95[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two-dimensional array, how to extract unique rows? (★★★)

In [98]:
Z = np.random.randint(0,2,(6,3))
print(Z)
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print("Unique rows: \n", uZ)

[[1 0 0]
 [0 0 0]
 [1 0 0]
 [1 0 1]
 [1 0 1]
 [0 1 0]]
Unique rows: 
 [[0 0 0]
 [0 1 0]
 [1 0 0]
 [1 0 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [99]:
A = np.random.randint(1,10,5)
B = np.random.randint(1,10,5)
print(A, B)
print("Sum A: ", np.einsum('i->', A)) # np.sum(A)
print("A * B:", np.einsum('i,i->i', A, B)) # A * B
print("Inner: ", np.einsum('i,i', A, B)) # np.inner(A, B)
print("Outer: \n", np.einsum('i,j', A, B)) # np.outer(A, B)

[8 1 3 7 6] [2 8 3 5 9]
Sum A:  25
A * B: [16  8  9 35 54]
Inner:  122
Outer: 
 [[16 64 24 40 72]
 [ 2  8  3  5  9]
 [ 6 24  9 15 27]
 [14 56 21 35 63]
 [12 48 18 30 54]]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [100]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [101]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
[2.0, 0.0, 1.0, 1.0],
[1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [102]:
X = np.random.randint(1, 10, 100)
N = 100
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[4.374 5.321]
